# Generated by Django 5.2.3 on 2025-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100)),
                ('descricao', models.TextField(blank=True, help_text='Descrição detalhada do produto', null=True)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do produto', max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, help_text='Data de criação do registro')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
